{
	imports = [
    ./twilight.nix
    ./ts-autotag.nix
		./lualine.nix
    ./luasnip.nix
    ./tmux.nix
		./neotree.nix
    ./tagbar.nix
		./toggleterm.nix
    ./lsp.nix
		./transparent.nix
    ./treesitter.nix
		./barbar.nix
		./nix.nix
    ./cmp.nix
    ./autoclose.nix
    ./mini.nix
    ./multicursors.nix
	];
}
